projects:
  prisma:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: prisma/prisma.yml
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: localhost:4000
