projects:
  database:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: prisma/prisma.yml
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: https://kl-demo-server-5da8d6f420.herokuapp.com/demo-server/dev